# Instala dependencias do sistema para o Chrome/Puppeteer
RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    ca-certificates \
    procps \
    libxss1 \
    libasound2 \
    libatk-bridge2.0-0 \
    libgtk-3-0 \
    libnss3 \
    libx11-xcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxi6 \
    libxtst6 \
    libgbm1 \
    libglib2.0-0 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Configura diretorio
WORKDIR /usr/src/app

# Copia dependencias e instala
COPY package*.json ./
RUN npm install

# Copia o codigo fonte
COPY . .

# Porta e inicializacao
EXPOSE 3001
CMD ["node", "server.js"]
